# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Tags
    url: tags/
    weight: 20
  - name: Blogs
    url: post/
    weight: 30
  - name: Journey
    url: journey/
    weight: 40
  - name: Projects
    url: game/
    weight: 50
  - name: About Me
    url: about_me/
    weight: 60

